[package]
name = "mercury"
version = "0.1.0"
edition = "2021"
description = "Cross-market prediction arbitrage engine"

[dependencies]
native-tls = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
ring = "0.17"
reqwest = { version = "0.12", features = ["json", "native-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tokio-native-tls = "0.3"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-native-tls", "chrono", "uuid", "rust_decimal"] }
alloy = { version = "0.8.2", features = ["full", "eip712"] }
alloy-sol-types = "0.8.26"
jsonwebtoken = "9"
rsa = { version = "0.9", features = ["pem"] }
rust_decimal = { version = "1", features = ["serde-with-str"] }
rust_decimal_macros = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
notify = "6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
anyhow = "1"
async-trait = "0.1"
futures-util = "0.3"
hex = "0.4"
sha2 = "0.10"
zeroize = { version = "1", features = ["derive"] }
tokio-util = "0.7"
lru = "0.12"
clap = { version = "4", features = ["derive"] }
tracing-appender = "0.2.4"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
